[[
  Context = "https://s-agent-comm.github.io/agent-ontology/context/agent.jsonld",
  Semantic = "https://s-agent-comm.github.io/agent-ontology/ontologies/intent.ttl",
  UnknownAttr = "agent:Foo"
]]
interface UnknownAttr {
  [Intent="agent:DoThing"]
  Promise<Result> doThing(Thing thing);
};
